#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

set_time_limit(0);
ini_set('memory_limit', '2048M');

use \ReviewParser\ParserFactory;
use \ReviewParser\Configuration;

try {
    $config        = require 'config.php';
    $configuration = new Configuration($argv, $config);

    $parser = ParserFactory::makeParser($configuration);
    $parser->getParsingResult();
} catch (\Exception $exception) {
    echo $exception->getMessage() . PHP_EOL;
}
